# Welcome to Serverless!
# Happy Coding!

service: lambda-uppercase

frameworkVersion: '3'

provider:
  name: aws
  runtime: java11
  region: us-east-2

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
